Repository spacebin-org/spirit, pull requests merged in 2020-06, with the labels that each got.

#8 docs: new CONTRIBUTORS file
  CONTRIBUTING.md
Labels: help wanted

#10 Create Issue Templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: ☄️ enhancement, 📖 documentation

#37 chore(merge): merge develop -> master
  .gitignore
  .swcrc
  README.md
  package.json
  src/controllers/document.controller.ts
  src/entities/document.entity.ts
  src/keyGenerator.ts
  src/routes/document.route.ts
  src/server.ts
  src/tests/keyGenerator.spec.ts
  src/tests/randomString.spec.ts
  tsconfig.json
  yarn.lock
Labels: ☄️ enhancement

#60 chore(badges): add Codacy badge
  README.md
Labels: 📖 documentation

#63 fix: dead/broken links to old name of organization
  README.md
Labels: 📖 documentation

#88 docs: Update OpenAPI Specification
  spec.yml
Labels: 📖 documentation

#89 Update Dockerfile
  Dockerfile
  README.md
Labels: ☄️ enhancement
